#include "Buildings.h"
#include <string>
using namespace std;

#ifndef INDUSTRIALBUILDING_H
#define INDUSTRIALBUILDING_H

/**
 * @class IndustrialBuilding
 * @brief Represents an industrial building, inheriting from Buildings.
 */
class IndustrialBuilding : public Buildings {

protected:
    string buildingName;          /**< Name of the industrial building. */
    string buildingType;          /**< Type of the industrial building. */
    Citizen* listOfCitizens;      /**< List of citizens associated with the building. */

    double maintenanceCost;       /**< Maintenance cost for the building. */
    int powerReq;                 /**< Power requirement of the building. */
    int waterReq;                 /**< Water requirement of the building. */
    int sewageCost;               /**< Sewage cost for the building. */
    Utility* resources;            /**< Mediator for managing resources. */

    float sales;                  /**< Sales generated by the building. */
    float profit;                 /**< Profit generated by the building. */
    int employment;               /**< Employment count in the building. */

    State* state;                 /**< Current state of the building. */

public:

    /**
     * @brief Gets the type of the industrial building.
     * @return The type of the building as a string.
     */
    virtual string getBuildingType() = 0;

    /**
     * @brief Gets the number of jobs created by the industrial building.
     * @return The number of jobs as an integer.
     */
    virtual int getJobsCreated() = 0;

    /**
     * @brief Gets the maintenance cost of the industrial building.
     * @return The maintenance cost as a double.
     */
    virtual double getMaintenanceCost() = 0;

    /**
     * @brief Gets the name of the industrial building.
     * @return The name of the building as a string.
     */
    virtual string getName() = 0;

    /**
     * @brief Gets the power requirement of the industrial building.
     * @return The power requirement as an integer.
     */
    virtual int getPowerReq() = 0;

    /**
     * @brief Gets the sewage cost of the industrial building.
     * @return The sewage cost as an integer.
     */
    virtual int getSewageCost() = 0;

    /**
     * @brief Gets the water requirement of the industrial building.
     * @return The water requirement as an integer.
     */
    virtual int getWaterReq() = 0;


    /**
     * @brief Requests the current state of the industrial building.
     */
    virtual void requestState() = 0;

    /**
     * @brief Gets the sales generated by the industrial building.
     * @return Sales amount as a float.
     */
    virtual float getSales() = 0;

    /**
     * @brief Gets the profit generated by the industrial building.
     * @return Profit amount as a float.
     */
    virtual float getProfit() = 0;

    /**
     * @brief Pays a citizen employed in the industrial building.
     * @return The payment amount as an integer.
     */
    virtual int payCitizen() = 0;

    /**
     * @brief sets the state of the building
     */
    virtual void setState(State* newState) = 0;
};

#endif

