#include "CommercialBuilding.h"
#include <string> 
using namespace std;

#ifndef MALL_H
#define MALL_H

/**
 * @class Mall
 * @brief Represents a mall, inheriting from CommercialBuilding.
 */
class Mall : public CommercialBuilding {
public:
    /**
     * @brief Constructs a Mall object.
     * @param bName Name of the mall.
     * @param pReq Power requirement.
     * @param wReq Water requirement.
     * @param mCost Maintenance cost.
     * @param sCost Sewage cost.
     * @param waste Waste produced.
     * @param sales Total sales.
     * @param profit Total profit.
     * @param emp Number of employees.
     */
    Mall(string bName,int pReq, int wReq, double mCost, int sCost, int waste, float sales, float profit, int emp);


    /**
     * @brief Gets the type of the mall.
     * @return The type of the mall as a string.
     */
    virtual string getBuildingType();

    /**
     * @brief Gets the number of jobs created by the mall.
     * @return The number of jobs as an integer.
     */
    virtual int getJobsCreated();

    /**
     * @brief Gets the maintenance cost of the mall.
     * @return The maintenance cost as a double.
     */
    virtual double getMaintenanceCost();

    /**
     * @brief Gets the name of the mall.
     * @return The name of the mall as a string.
     */
    virtual string getName();

    /**
     * @brief Gets the power requirement of the mall.
     * @return The power requirement as an integer.
     */
    virtual int getPowerReq();

    /**
     * @brief Gets the sewage cost of the mall.
     * @return The sewage cost as an integer.
     */
    virtual int getSewageCost();

    /**
     * @brief Gets the water requirement of the mall.
     * @return The water requirement as an integer.
     */
    virtual int getWaterReq();

    /**
     * @brief Requests the current state of the mall.
     */
    virtual void requestState();

    /**
     * @brief sets the state of the building
     */
    void setState(State* newState);

    /**
     * @brief Gets the income generated by the mall.
     * @return The income as an integer.
     */
    int getIncome();

    /**
     * @brief Gets the waste cost for the mall.
     * @return The waste cost as an integer.
     */
    int getWasteCost();

    /**
     * @brief Gets the total sales of the mall.
     * @return The sales as a float.
     */
    float getSales();

    /**
     * @brief Gets the total profit of the mall.
     * @return The profit as a float.
     */
    float getProfit();

    /**
     * @brief Pays a citizen from the mall's profits.
     * @return The payment amount as an integer.
     */
    int payCitizen();

 /**
     * @brief gets the current income of a commercial building
     * @return the income as an integer
     */
    virtual int getCommercialIncome();

    /**
     * @brief gets the current income of a commercial building
     * @return the income as an integer
     */
    virtual double getBalance();

    /**
     * @brief gets the current income of a commercial building
     * @return the income as an integer
     */
    virtual void setBalance(double b);

    /**
     * @brief Receives power for the building.
     * @return true if power was received successfully, false otherwise.
     */
    virtual bool getPower();

    /**
     * @brief Receives water for the building.
     * @return true if water was received successfully, false otherwise.
     */
    virtual bool getWater();

    /**
     * @brief Cleans the waste of the building.
     * @return true if waste cleaning was successful, false otherwise.
     */
    virtual bool cleanWaste();

    /**
     * @brief Cleans the sewage of the building.
     * @return true if sewage cleaning was successful, false otherwise.
     */
    virtual bool cleanSewage();

    /**
	 * @brief Add a building to the Building
	 * 
	 * @param building The building to add to the WaterSupply
	 */
	virtual void addBuilding();
};

#endif

