#include "PublicServiceBuilding.h"
#include <string>
using namespace std;

#ifndef SCHOOL_H
#define SCHOOL_H

/**
 * @class School
 * @brief Class representing a school, inheriting from PublicServiceBuilding.
 */
class School : public PublicServiceBuilding {
protected:
    // Building details
    string buildingName; ///< Name of the building
    string buildingType; ///< Type of the building
    Citizen* listOfCitizens; ///< List of citizens associated with the building

    // Resource and maintenance requirements
    double maintenanceCost; ///< Cost required for maintenance
    int powerReq; ///< Power requirement for the building
    int waterReq; ///< Water requirement for the building
    int sewageCost; ///< Sewage cost for the building
    int waste; ///< Waste generated by the building
    int employment; ///< Employment generated by the building
    float educationCoverage; ///< Coverage of education provided by the school

    // Resource mediator and state
    ResourceMediator* resources; ///< Mediator for resources
    State* state; ///< Current state of the building

public:
    /**
     * @brief Constructs a School object.
     * @param bName Name of the school.
     * @param pReq Power requirement.
     * @param wReq Water requirement.
     * @param mCost Maintenance cost.
     * @param sCost Sewage cost.
     * @param waste Waste produced.
     * @param employment Employment opportunities.
     * @param eCov Education coverage.
     */
    School(string bName, int pReq, int wReq, double mCost, int sCost, int waste, int employment, float eCov);

    /**
     * @brief Gets the type of building.
     * @return Type of the building as a string.
     */
    virtual string getBuildingType();

    /**
     * @brief Gets the water requirement of the school.
     * @return Water requirement as an integer.
     */
    virtual int getWaterReq();

    /**
     * @brief Gets the number of jobs created by the school.
     * @return Number of jobs created.
     */
    virtual int getJobsCreated();

    /**
     * @brief Gets the maintenance cost of the school.
     * @return Maintenance cost as a double.
     */
    virtual double getMaintenanceCost();

    /**
     * @brief Gets the name of the school.
     * @return Name of the school as a string.
     */
    virtual string getName();

    /**
     * @brief Gets the power requirement of the school.
     * @return Power requirement as an integer.
     */
    virtual int getPowerReq();

    /**
     * @brief Gets the sewage cost of the school.
     * @return Sewage cost as an integer.
     */
    virtual int getSewageCost();

    /**
     * @brief Gets the waste cost associated with the school.
     * @return Waste cost as an integer.
     */
    virtual int getWasteCost();

    /**
     * @brief Requests the current state of the school.
     */
    virtual void requestState();

    /**
     * @brief Gets the education coverage provided by the school.
     * @return Education coverage as a float.
     */
    float getEducationCoverage();

    /**
     * @brief sets the state of the building
     */
    void setState(State* newState);
};

#endif
