#ifndef UTILITIESCONTROL_H
#define UTILITIESCONTROL_H

#include "CitySector.h"
#include "Utility.h"
#include "UtilityPowerPlant.h"
#include "WaterSupply.h"
#include "WasteManagement.h"
#include "SewageSystems.h"

class UtilitesControl
{
private:
    /**
     * @class ListOfUtilites
     * @brief Lists of Utilities
     * Class uses a list of Utilities to loop through each Utility to acquire data
     */
    Utility **ListOfUtilites;
    /**
     * @class amountOfUtil
     * @brief Amount of Utilities in the list
     * Variable to hold the amount of Utilities To loop through the list
     */
    int amountOfUtil;

public:
    UtilitesControl(/* args */);
    ~UtilitesControl();

    /**
     * @class getTotalPower
     * @brief Gets Total amount of Power from the City
     * Return the amount of Power generated by Power Utilities To the city
     * Player can see the amount of Power available in the city and act accordingly
     */
    int getTotalPower();
    /**
     * @class getTotalSewage
     * @brief Gets Total amount of Sewage Managment from the City
     * Return the amount of Sewage that the City can handle
     */
    int getTotalSewage();
    /**
     * @class getTotalWaste
     * @brief Gets Total amount of Waste Managment from the City
     * Return the amount of waste that the City can handle
     */
    int getTotalWaste();
    /**
     * @class getTotalWater
     * @brief Gets Total amount of Waster Generation from the City
     * Return the amount of Usable Water that the City can Create
     */
    int getTotalWater();

    /**
     * @class addUtilities
     * @brief Adds a Utilities to the list
     * Adds the Utilities to the list to be used by the Interface
     */
    void addUtilities(Utility *add);
    /**
     * @class removeUtilities
     * @brief Removes A Utility From the List
     * Removes the Utility from the list.
     * This could be due to a Utility being destroyed or Damaged and requires repair .
     */
    void removeUtilities(Utility *rem);
    /**
     * @class getAmountOfUtilities
     * @brief Returns the amount of Utilites
     * Returns the amount of Utilities in the list
     * The Player could see the amount of Utilities in the city for clarity
     */
    int getAmountOfUtilities();
};

#endif
