#include "IndustrialBuilding.h"
#include <string>

using namespace std;

#ifndef WAREHOUSE_H
#define WAREHOUSE_H

/**
 * @class Warehouse
 * @brief Represents a warehouse building, inheriting from IndustrialBuilding.
 */
class Warehouse : public IndustrialBuilding {

protected:
    // Basic building details
    string buildingName; ///< The name of the warehouse building.
    string buildingType; ///< The type of the building (e.g., "Warehouse").
    Citizen* listOfCitizens; ///< List of citizens associated with the building.

    // Resource and cost requirements
    double maintenanceCost; ///< The maintenance cost of the warehouse.
    int powerReq; ///< The power requirement for the warehouse.
    int waterReq; ///< The water requirement for the warehouse.
    int sewageCost; ///< The sewage cost for the warehouse.
    int waste; ///< The waste produced by the warehouse.
    ResourceMediator* resources; ///< Mediator for handling resource management.

    // Business metrics
    float sales; ///< Total sales made by the warehouse.
    float profit; ///< Profit generated by the warehouse.
    int employment; ///< Number of jobs created by the warehouse.

    // Current building state
    State* state; ///< The current state of the warehouse.

public:
    /**
     * @brief Constructor for the Warehouse class.
     * @param bName The name of the warehouse.
     * @param pReq The power requirement.
     * @param wReq The water requirement.
     * @param mCost The maintenance cost.
     * @param sCost The sewage cost.
     * @param waste The waste produced by the warehouse.
     * @param employment The number of jobs created.
     */
    Warehouse(string bName, int pReq, int wReq, double mCost, int sCost, int waste, int employment);

    /**
     * @brief Cleans the sewage of the warehouse.
     * @return True if sewage is successfully cleaned, false otherwise.
     */
    virtual bool cleanSewage();

    /**
     * @brief Cleans the waste of the warehouse.
     * @return True if waste is successfully cleaned, false otherwise.
     */
    virtual bool cleanWaste();

    /**
     * @brief Gets the type of the building.
     * @return The building type as a string.
     */
    virtual string getBuildingType();

    /**
     * @brief Gets the number of jobs created by the warehouse.
     * @return The number of jobs created.
     */
    virtual int getJobsCreated();

    /**
     * @brief Gets the maintenance cost of the warehouse.
     * @return The maintenance cost as a double.
     */
    virtual double getMaintenanceCost();

    /**
     * @brief Gets the name of the warehouse.
     * @return The name of the warehouse as a string.
     */
    virtual string getName();

    /**
     * @brief Gets the power requirement of the warehouse.
     * @return The power requirement as an integer.
     */
    virtual int getPowerReq();

    /**
     * @brief Gets the sewage cost of the warehouse.
     * @return The sewage cost as an integer.
     */
    virtual int getSewageCost();

    /**
     * @brief Gets the water requirement of the warehouse.
     * @return The water requirement as an integer.
     */
    virtual int getWaterReq();

    /**
     * @brief Performs an operation related to the warehouse.
     */
    virtual void operation();

    /**
     * @brief Pays the maintenance cost of the warehouse.
     * @return True if payment is successful, false otherwise.
     */
    virtual bool payMaintenance();

    /**
     * @brief Receives power for the warehouse.
     * @return True if power is successfully received, false otherwise.
     */
    virtual bool receivePower();

    /**
     * @brief Receives water for the warehouse.
     * @return True if water is successfully received, false otherwise.
     */
    virtual bool receiveWater();

    /**
     * @brief Requests the current state of the warehouse.
     */
    virtual void requestState();

    /**
     * @brief Gets the waste cost of the warehouse.
     * @return The waste cost as an integer.
     */
    int getWasteCost();

   /**
     * @brief sets the state of the building
     */
    void setState(State* newState);
    // Additional functions

    /**
     * @brief Gets the total sales made by the warehouse.
     * @return The total sales as a float.
     */
    float getSales();

    /**
     * @brief Gets the profit generated by the warehouse.
     * @return The profit as a float.
     */
    float getProfit();

    /**
     * @brief Pays a citizen associated with the warehouse.
     * @return The payment amount as an integer.
     */
    int payCitizen();
};

#endif

