#include <string>
#include "Buildings.h"
using namespace std;

#ifndef COMMERCIALBUILDING_H
#define COMMERCIALBUILDING_H

// Forward declarations
class Citizen;
class ResourceMediator;
class State;

/**
 * @brief Abstract base class representing commercial buildings in the simulation
 * @details This class extends the Buildings base class and implements specific
 *          functionality for commercial structures such offices ,shops and malls
 */
class CommercialBuilding : Buildings {
protected:
    /** @brief Name identifier for the commercial building */
    string buildingName;
    
    /** @brief Type category of the commercial building */
    string buildingType;
    
    /** @brief List of citizens working in or associated with this building */
    Citizen* listOfCitizens;
    
    /** @brief Monthly maintenance cost for the building */
    double maintenanceCost;
    
    /** @brief Power requirement for the building in units */
    int powerReq;
    
    /** @brief Water requirement for the building in units */
    int waterReq;
    
    /** @brief Sewage cost for the building in units */
    int sewageCost;
    
    /** @brief Mediator for handling resource distribution */
    ResourceMediator* resources;
    
    /** @brief Total sales revenue generated by the building */
    float sales;
    
    /** @brief Net profit after deducting costs from sales */
    float profit;
    
    /** @brief Number of citizens currently employed in the building */
    int employment;
    
    /** @brief Pointer to the state object managing this building */
    State* state;

public:
    // Pure virtual functions inherited from Buildings
    
    /**
     * @brief Handles sewage cleaning for the commercial building
     * @return true if sewage was successfully cleaned, false otherwise
     */
    virtual bool cleanSewage() = 0;
    
    /**
     * @brief Handles waste cleaning for the commercial building
     * @return true if waste was successfully cleaned, false otherwise
     */
    virtual bool cleanWaste() = 0;
    
    /**
     * @brief Gets the type of the commercial building
     * @return Building type as string
     */
    virtual string getBuildingType() = 0;
    
    /**
     * @brief Gets the number of jobs created by this commercial building
     * @return Number of jobs as integer
     */
    virtual int getJobsCreated() = 0;
    
    /**
     * @brief Gets the maintenance cost of the commercial building
     * @return Monthly maintenance cost in currency units
     */
    virtual double getMaintenanceCost() = 0;
    
    /**
     * @brief Gets the name of the commercial building
     * @return Building name as string
     */
    virtual string getName() = 0;
    
    /**
     * @brief Gets the power requirement of the commercial building
     * @return Power requirement in units
     */
    virtual int getPowerReq() = 0;
    
    /**
     * @brief Gets the sewage cost of the commercial building
     * @return Sewage cost in units
     */
    virtual int getSewageCost() = 0;
    
    /**
     * @brief Gets the water cost of the commercial building
     * @return Water cost in units
     */
    virtual int getWaterCost() = 0;
    
    /**
     * @brief Main operation function for the commercial building
     * @details Handles primary business operations and resource management
     */
    virtual void operation() = 0;
    
    /**
     * @brief Processes maintenance payment for the commercial building
     * @return true if maintenance was successfully paid, false otherwise
     */
    virtual bool payMaintenance() = 0;
    
    /**
     * @brief Handles power reception for the commercial building
     * @return true if power was successfully received, false otherwise
     */
    virtual bool receivePower() = 0;
    
    /**
     * @brief Handles water reception for the commercial building
     * @return true if water was successfully received, false otherwise
     */
    virtual bool receiveWater() = 0;
    
    /**
     * @brief Requests the current state of the commercial building
     */
    virtual void requestState() = 0;

    // Additional commercial-specific functions
    
    /**
     * @brief Gets the total sales revenue of the commercial building
     * @return Total sales in currency units
     */
    float getSales();
    
    /**
     * @brief Secondary operation function for additional business processes
     * @details Handles supplementary operations specific to commercial buildings
     */
    void operation2();
    
    /**
     * @brief Gets the net profit of the commercial building
     * @return Net profit in currency units
     */
    float getProfit();
};

#endif
