#include "ResidentialBuilding.h"
#include <string>
using namespace std;

#ifndef HOUSE_H
#define HOUSE_H

/**
 * @brief Class representing a residential house in the simulation
 * @details This class implements the ResidentialBuilding abstract class and provides
 *          specific functionality for individual houses, including resident management,
 *          utility consumption, and maintenance operations
 */
class House : ResidentialBuilding {
protected:
    /** @brief Name identifier for the house */
    string buildingName;
    
    /** @brief Type category of the house */
    string buildingType;
    
    /** @brief Maximum number of residents that can live in the house */
    int capacity;
    
    /** @brief List of citizens currently residing in the house */
    Citizen* listOfCitizens;
    
    /** @brief Monthly maintenance cost for the house */
    double maintenanceCost;
    
    /** @brief Power requirement for the house in units */
    int powerReq;
    
    /** @brief Water requirement for the house in units */
    int waterReq;
    
    /** @brief Sewage cost for the house in units */
    int sewageCost;
    
    /** @brief Amount of waste generated by the house */
    int waste;
    
    /** @brief Mediator for handling resource distribution */
    ResourceMediator* resources;
    
    /** @brief Pointer to the state object managing this house */
    State* state;

public:
    /**
     * @brief Constructor for the House class
     * @param bName Name of the house
     * @param pReq Power requirement
     * @param wReq Water requirement
     * @param mCost Maintenance cost
     * @param sCost Sewage cost
     * @param waste Waste generation rate
     * @param capacity Maximum number of residents
     */
    House(string bName, int pReq, int wReq, double mCost, int sCost, int waste, int capacity);
    
    /**
     * @brief Handles sewage cleaning for the house
     * @return true if sewage was successfully cleaned, false oth
